/**
 * RFB Server (Windows Driver) - A JNA based driver for Windows,
 * Copyright © 2006 SSHTOOLS Limited (support@sshtools.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sshtools_rfbserver_windows_jni_HookTest */

#ifndef _Included_com_sshtools_rfbserver_windows_jni_HookTest
#define _Included_com_sshtools_rfbserver_windows_jni_HookTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sshtools_rfbserver_windows_jni_HookTest
 * Method:    registerHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sshtools_rfbserver_windows_jni_HookTest_registerHook
  (JNIEnv *, jobject);

/*
 * Class:     com_sshtools_rfbserver_windows_jni_HookTest
 * Method:    unRegisterHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sshtools_rfbserver_windows_jni_HookTest_unRegisterHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
