/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sshtools_rfbserver_windows_jni_HookTest */

#ifndef _Included_com_sshtools_rfbserver_windows_jni_HookTest
#define _Included_com_sshtools_rfbserver_windows_jni_HookTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sshtools_rfbserver_windows_jni_HookTest
 * Method:    registerHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sshtools_rfbserver_windows_jni_HookTest_registerHook
  (JNIEnv *, jobject);

/*
 * Class:     com_sshtools_rfbserver_windows_jni_HookTest
 * Method:    unRegisterHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sshtools_rfbserver_windows_jni_HookTest_unRegisterHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
